# Generated by Django 2.2.8 on 2020-02-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('category', models.CharField(choices=[('WD', 'Web Development'), ('GD', 'Graphic Development'), ('MA', 'Mobile App Development'), ('DM', 'Digital Marketing'), ('CW', 'Copy Writing'), ('SM', 'Social Media Management')], max_length=2)),
                ('duration', models.DateTimeField()),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('price_range', models.IntegerField()),
                ('photo', models.ImageField(upload_to='projects/')),
                ('payment_method', models.CharField(choices=[('MM', 'Mobile Money'), ('CD', 'Bank / Credit Card')], max_length=2)),
            ],
        ),
    ]
