# Generated by Django 2.2.8 on 2020-02-27 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('category', models.CharField(choices=[('WD', 'Web Development'), ('GD', 'Graphic Design'), ('MA', 'Mobile App Development'), ('DM', 'Digital Marketing'), ('CW', 'Copy Writing'), ('SM', 'Social Media Management')], max_length=2)),
                ('duration', models.DateField()),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('price_range', models.IntegerField()),
                ('photo', models.ImageField(upload_to='projects/')),
                ('payment_method', models.CharField(choices=[('MM', 'Mobile Money'), ('CD', 'Bank / Credit Card')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('date_assigned', models.DateTimeField(auto_now=True)),
                ('date_completed', models.DateField(null=True)),
                ('revoke', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now=True)),
                ('requested_amount', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=250)),
                ('creatd_on', models.DateTimeField(auto_now=True)),
                ('read', models.BooleanField(default=False)),
                ('read_on', models.DateTimeField(null=True)),
                ('link', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
