# Generated by Django 2.2.8 on 2020-02-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('WD', 'Web Development'), ('GD', 'Graphic Design'), ('MA', 'Mobile App Development'), ('DM', 'Digital Marketing'), ('CW', 'Copy Writing'), ('SM', 'Social Media Management')], max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.DateField(),
        ),
    ]
