# Generated by Django 2.2.8 on 2020-02-18 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_completed', models.BooleanField(default=False)),
                ('account_type', models.CharField(max_length=250)),
                ('mobile', models.IntegerField()),
                ('skills', models.CharField(choices=[('WD', 'Web Development'), ('GD', 'Graphic Development'), ('MA', 'Mobile App Development'), ('DM', 'Digital Marketing'), ('CW', 'Copy Writing'), ('SM', 'Social Media Management')], max_length=2)),
                ('about', models.TextField()),
                ('region', models.CharField(choices=[('GA', 'Greater Accra'), ('AR', 'Ashanti Region'), ('ER', 'Eastern Region'), ('VR', 'Volta Region'), ('NR', 'Northern Region')], max_length=2)),
                ('experience', models.CharField(choices=[('BG', 'Beginner'), ('IT', 'Intermmediate'), ('AD', 'Advanced')], max_length=2)),
                ('profile_image', models.ImageField(upload_to='profiles/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
