# Generated by Django 2.2.8 on 2020-02-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200219_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(choices=[('WD', 'Web Development'), ('GD', 'Graphic Design'), ('MA', 'Mobile App Development'), ('DM', 'Digital Marketing'), ('CW', 'Copy Writing'), ('SM', 'Social Media Management')], max_length=2),
        ),
    ]
